### ISSUE TITLE
Implemented design on a Zynq no PC -> FPGA communication

### ISSUE THREAD

**Issue by gswdh** [WangXuan95/FPGA-ftdi245fifo#13]
I have this core implemented in a Zynq with a DMA implemented to send and receive data from the FTDI core which is connected to an FT601. However, sending data from the PC to the FPGA does not work, FPGA -> PC does work.

I have tested my DMA on the Zynq via a loop back - working great.

A loop back with or without a FIFO on the IP core does not work.

With the DMA connected to the IP core does not work.

I did have to manually implement two of the parameters as follows due to synth error in Vivado.

```
localparam  CHIP_EW               = 2;
localparam  CHIP_DRIVE_AT_NEGEDGE = 0;
```

The project I have it implemented in is in this project https://github.com/gswdh/CameraFPGA/tree/develop

I wonder if there's any advice or example project of implementing this core on a Xilinx device.

**Comment by josephorender** [comment]
I have the same issue. I am using a Zedboard with a UMFT601x FMC card. Here is the block design

![image](https://github.com/WangXuan95/FPGA-ftdi245fifo/assets/129799349/30b08271-fa21-4353-b263-1795a59dd35e)

![image](https://github.com/WangXuan95/FPGA-ftdi245fifo/assets/129799349/f7e37ac7-b110-4ea8-bdef-511e33205102)

![image](https://github.com/WangXuan95/FPGA-ftdi245fifo/assets/129799349/b7938fe0-b2d9-4be9-9f4d-06c8b324502a)

Nothing ever comes out the axi stream.

**Comment by gswdh** [comment]
@josephorender what happens if you send more data? Perhaps there needs to be enough to justify a flush somewhere?

**Comment by josephorender** [comment]
@gswdh I pulled your project and noticed you are using Vivado 2023.2. Im using 2023.1. Either way, I think the out of context runs are causing problems with this guys code. Vivado will delete half the tristate buffers in one of his fifo blocks. You need to set this:
![image](https://github.com/WangXuan95/FPGA-ftdi245fifo/assets/129799349/df0af8a5-2496-4730-855c-3d8afe992635)
and it will keep the buffers. I followed the Critical warnings until they were gone, but I can still get the loopback to work even with timing currently failing. 
![image](https://github.com/WangXuan95/FPGA-ftdi245fifo/assets/129799349/bba8f2fb-cbac-4ea4-9ed7-0b5ad934bd45)
Hope this helps!

**Comment by josephorender** [comment]
![image](https://github.com/WangXuan95/FPGA-ftdi245fifo/assets/129799349/fd7986e8-e99e-4847-9cac-cec64d8ca597)

**Comment by gswdh** [comment]
Nice work @josephorender unfortunealy I decided to drop the FT601 for the gigabit ethernet on the Zynq. Is your issue solved now?

**Comment by josephorender** [comment]
It is. I bet they were related. You can probably close this one out.

**Comment by gswdh** [comment]
Thanks, all the best!
