### ISSUE TITLE
您好,方便请教一些问题吗?

### ISSUE THREAD

**Issue by Spark8688** [WangXuan95/FPGA-ftdi245fifo#3]
您好:
我的开发版是Altera DE10-standard,
目前运行此程式码时遇到一些问题,
在FT245 sync fifo模式下,
会有部分字节错误的情况,
但是在big bang模式下,
可以正常运行无字节错误,
请问您是否可以提供我一些帮助,
或是您是否方便提供您的联系方式吗感谢!

**Comment by WangXuan95** [comment]
你好，
请提供你的QQ，我加你

**Comment by Spark8688** [comment]
您好:
这是我的QQ，6912​​14170，麻烦你了，谢谢。
