### ISSUE TITLE
FTDI-245fifo回测试速率低

### ISSUE THREAD

**Issue by skyskyskysky** [WangXuan95/FPGA-ftdi245fifo#5]
方便请教您关于
FTDI-245fifo
的一些问题吗
您测试出来的42MB是用啥程序测的哇
如果可以，可以加下qq吗1039397206

**Comment by WangXuan95** [comment]
你好，请仔细看我的库，里面不仅包括硬件工程，还有驱动和软件的安装和部署方法，我用的是 Python 3.x，在 Windows10 64位系统上测试的。
