### ISSUE TITLE
大佬，我想问一下怎么传输文件

### ISSUE THREAD

**Issue by sugolet** [WangXuan95/FPGA-ftdi245fifo#6]
我用tx函数填写文件路径结果传输的是字符串，我py小白所以不是很懂

**Comment by WangXuan95** [comment]
哪有 TX 函数？我根本没写 TX 函数啊

**Comment by WangXuan95** [comment]
我在 Python 样例代码里只写了发送字符串的函数。需要你自己学一下 Python ，去加载文件内容并发送的功能

**Comment by sugolet** [comment]
能加个联系方式咨询一下吗

**Comment by WangXuan95** [comment]
是不是设备名字变了，python程序是指定设备名来找到USB设备的，你看python中有这样一句：
```python
usb = USB_FT232H_sync245mode(b'USB <-> Serial Converter')
```
意思就是说 USB 设备名必须是 `USB <-> Serial Converter` 它才能打开。你可以在 FT_Prog 软件里查看和修改这个名字。

我的 QQ 是 629708558
