### ISSUE TITLE
FGPA板子名稱

### ISSUE THREAD

**Issue by Steve-deltora** [WangXuan95/FPGA-ftdi245fifo#8]
目前我正在嘗試重新pin assignment到我的FPGA上，但不確定有沒有pin對，所以想請問您用的是哪塊板子，想藉由這個您pin的板子回推我pin的正不正確。

**Comment by WangXuan95** [comment]
你好，我用的是我自己画的FPGA板，而不是现有的开发板，所以没有参考价值。不过我今天更新了更详细的引脚连接说明，请看 README.md

**Comment by Steve-deltora** [comment]
真的是大神，太厲害了🤙🤙🤙
